### ISSUE TITLE
Consider to introduce an interface

### ISSUE THREAD

**Issue by theofidry** [OndraM/ci-detector#64]
Instead of having a base non-final class `CiDetector` I would like to recommend to introduce an interface `CiDetector` and rename the current one to `DefaultCiDetector`.

The rational being it could be interesting to provide multiple implementations, for example:

- A `MemoizedCiDetector` which would be a decorator memoizing the results – not all processes may change of CI environment mid-way
- A `NullCiDetector`

**Comment by OndraM** [comment]
Ok, my idea for next major version is:
- Create new `CiDetectorInterface`
- Keep `CiDetector` class name, but make it implement `CiDetectorInterface`
- Declare `CiDetector` constructor or maybe rather the whole class final, to solve unsafe `new static()` introduced in #65 

Will this work for your usecases?

**Comment by theofidry** [comment]
I'm not fond of the interface suffix, but that's a nitpick I can live with :)

>Declare CiDetector constructor or maybe rather the whole class final

I think that, in the context of when there is an interface, begs the question of what you expect the class to be extended for and if inheritance is the right choice there of if there might be a better way.

But with those changes already that would indeed work out more nicely already for us

**Comment by OndraM** [comment]
Hi @theofidry , could you have a look on https://github.com/OndraM/ci-detector/pull/94, to see if its fine for your use case?

**Comment by theofidry** [comment]
@OndraM sorry I missed your ping; At first glance it fits the bill I'll see if I can come up with a new implementation for infection soonish
