### ISSUE TITLE
No detect ci github-actions.

### ISSUE THREAD

**Issue by terabytesoftw** [OndraM/ci-detector#74]
| Q                | A
| ---------------- | ---
| Version             |  3.3.0
| PHP version      |  7.4.7
| CI | github actions.
|workflow|https://github.com/yii-extension/app/actions/runs/134544425/workflow
|issue| https://github.com/infection/infection/issues/1272

No detect CI github-actions in testing muting infection.

**Comment by OndraM** [comment]
Hi,
GitHub actions detection seems to be working as expected - here you can see dump of detected properties from actual Github Actions workflow: https://github.com/OndraM/ci-detector/runs/771770893?check_suite_focus=true#step:6:6 

Isn't possible the env variables are not available in the script? You can try running "env" command in github workflow to see the actual environment variables.

**Comment by OndraM** [comment]
I investigated your workflow a bit more, and find the issue.

You are running infection using sudo. However when using sudo, GitHub Actions does not set required environment variables for the sudo shell, making CI detection impossible.

I suggest not to run commands via sudo in your workflow. Unfortunately, this is behavior of GH actions and there is nothing I can do about it, sorry.
