### ISSUE TITLE
Add head branch retrieval support

### ISSUE THREAD

**Issue by sanmai** [OndraM/ci-detector#82]
For pull request builds it is essential to know against which base branch they are made against. 

For example:
- On GitHub Workflows it will be `$GITHUB_BASE_REF`
- On [Travis CI it will be `$TRAVIS_BRANCH`](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables).

Please consider adding head branch retrieval support.

More-less complete list:

- [x] AppVeyor `APPVEYOR_REPO_BRANCH` [(ref)](https://www.appveyor.com/docs/environment-variables/)
- [x] AWS CodeBuild - [seems to be none](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html)
- [x] AzurePipelines `SYSTEM_PULLREQUEST_TARGETBRANCH`
- [x] Bamboo `bamboo.repository.pr.targetBranch` [(ref)](https://confluence.atlassian.com/bamboo/bamboo-variables-289277087.html#Bamboovariables-Build-specificvariables)
- [x] Bitbucket Pipelines `BITBUCKET_PR_DESTINATION_BRANCH`
- [x] Buddy `BUDDY_EXECUTION_PULL_REQUEST_BASE_BRANCH`
- [x] CircleCI - [There's none.](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables)
- [x] Codeship [(there's none)](https://docs.cloudbees.com/docs/cloudbees-codeship/latest/pro-builds-and-configuration/environment-variables#_default_environment_variables)
- [x] continuousphp - [there's none](https://doc.continuousphp.com/environment-variables/#built-in-environment-variables)
- [x] codefresh.io `CF_PULL_REQUEST_TARGET` (CF is not yet supported here)
- [x] drone `DRONE_TARGET_BRANCH`
- [x] GitHub Actions `GITHUB_BASE_REF`
- [x] GitLab, either `CI_MERGE_REQUEST_TARGET_BRANCH_NAME` or `CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME`
- [x] Jenkins - [seems to be none](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#using-environment-variables)
- [x] TeamCity - [None found.](https://www.jetbrains.com/help/teamcity/predefined-build-parameters.html#Branch-Related+Parameters)
- [x] Travis CI `TRAVIS_BRANCH`
- [x] Wercker - [there's none](https://devcenter.wercker.com/administration/environment-variables/available-env-vars/).

For some cases it's just `CI_TARGET_BRANCH`.

**Comment by OndraM** [comment]
Hi @sanmai , thanks for the idea! This may be possible, however I'm not sure how widely supported is this feature by CIs. It is supported by Travis and GitHub Actions, I'm not sure about the others, can you have a look?

**Comment by sanmai** [comment]
I did just that. For a substantial part of the list I used work of [these fabulous folks](https://github.com/siddharthkp/ci-env/pull/36/files).

**Comment by OndraM** [comment]
@sanmai Cool! This means it is supported by 8/15 CI server supported by this library, so it makes sense to implement it :). 

Are you interested in implementing the feature?

It should be straightforward:
- extend `CiInterface` with method maybe `getGitBaseBranch` (or if you have different idea?).
- implement it for each CI server, maybe with condition when applicable, something like
```php
    public function getGitBaseBranch(): string
    {
        if ($this->isPullRequest()->yes()) {
            return $this->env->get('...'),
        } 

        return '';
    }
```
- (when build is not PR osbase branch cannot be detected, I think we can simply return empty string)
- extend tests: base test (= "not PR build") should assert for all CIs the method returns empty string
- PullRequest tests should assert target branch name (or empty string if not supported)

**Comment by OndraM** [comment]
What do you think @sanmai? 

I like the idea and I can add it to may backlog, but it may take a while, so help would be very much welcomed :).

**Comment by sanmai** [comment]
I'm very positive about this, but let me finish vacationing and I'll get to this.

**Comment by OndraM** [comment]
On Azure Pipelines it will be `SYSTEM_PULLREQUEST_TARGETBRANCH` - see environment variables dump: https://github.com/OndraM/ci-detector/pull/90/files#diff-9c8014bb2ba68223ecaea2ed39c2b16c043b56e983088f823484e0d63bcc3f73R136-R139

**Comment by sanmai** [comment]
It took quite a bit of time for me to get around, but here we are. The PR is ready for a review. 

- It uses `getTargetBranch(): string` because mentioning Git here is redundant: it doesn't add anything a user doesn't already know. It might make sense to remove `Git` designation from other methods too.
- It does not check for PR branch because it is not our call make this check. A CI might have this variable even if we don't know for certain if a build is a PR build. And it is a lot simpler this way.
