### ISSUE TITLE
Use TRAVIS_BUILD_WEB_URL instead of a hard coded URL

### ISSUE THREAD

**Issue by williamdes** [OndraM/ci-detector#85]
See: `TRAVIS_BUILD_WEB_URL` in https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

https://github.com/OndraM/ci-detector/blob/a48b539dc62859b33ecf0b919e3a175e9305fbab/src/Ci/Travis.php#L11

**Comment by OndraM** [comment]
Actually, Travis [now even has](https://changelog.travis-ci.com/new-environment-variables-build-url-and-job-url-74083) `TRAVIS_JOB_WEB_URL` variable, so the URL could be retrieved directly from it.
